[lint]
select = [

# Pyflakes
"F",
# pycodestyle
"E",
"W",
# isort
"I",
# pep8-naming
"N",
# pyupgrade
"UP",
# flake8-todos
"TD",
# flake8-tidy-imports
"TID",
# flake8-import-conventions
"ICN",
# flake8-bugbear
"B",
# flake8-bandit
"S",
# flake8-simplify
"SIM",
]

[lint.pydocstyle]
# Use Google-style docstrings.
convention = "pep257"

[lint.per-file-ignores]
"src/array_numbers/*" = ["E501"]