name: Quality code worflow
on: [ push, pull_request ]

jobs:
  quality-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install the project dependencies
        run: poetry install

      - name: Ruff Linter
        run: poetry run ruff check .

      - name: Run unit tests
        run: poetry run python -m pytest -v